//! Static registry of AMD processor and platform features.

use crate::model::{Category, FeatureDef, Privilege};
use Category::*;

#[rustfmt::skip]
pub const FEATURES: &[FeatureDef] = &[
    // Instruction set
    k("sse", "SSE", Isa, "128-bit single-precision SIMD", "sse"),
    k("sse2", "SSE2", Isa, "128-bit double-precision and integer SIMD", "sse2"),
    k("sse3", "SSE3", Isa, "Horizontal SIMD and unaligned loads", "pni"),
    k("ssse3", "SSSE3", Isa, "Byte shuffle and horizontal integer operations", "ssse3"),
    k("sse4_1", "SSE4.1", Isa, "Blend, dot-product, and rounding instructions", "sse4_1"),
    k("sse4_2", "SSE4.2", Isa, "String comparison and CRC32", "sse4_2"),
    k("sse4a", "SSE4a", Isa, "AMD streaming and misaligned-vector instructions", "sse4a"),
    k("avx", "AVX", Isa, "256-bit floating-point SIMD", "avx"),
    k("avx2", "AVX2", Isa, "256-bit integer SIMD", "avx2"),
    k("avx_vnni", "AVX-VNNI", Isa, "Vector integer dot products", "avx_vnni"),
    k("avx512f", "AVX-512F", Isa, "512-bit SIMD foundation", "avx512f"),
    k("avx512dq", "AVX-512DQ", Isa, "AVX-512 doubleword and quadword operations", "avx512dq"),
    k("avx512cd", "AVX-512CD", Isa, "AVX-512 conflict detection", "avx512cd"),
    k("avx512bw", "AVX-512BW", Isa, "AVX-512 byte and word operations", "avx512bw"),
    k("avx512vl", "AVX-512VL", Isa, "AVX-512 vector-length extensions", "avx512vl"),
    k("avx512ifma", "AVX-512IFMA", Isa, "AVX-512 integer fused multiply-add", "avx512ifma"),
    k("avx512vbmi", "AVX-512VBMI", Isa, "AVX-512 byte manipulation", "avx512vbmi"),
    k("avx512vbmi2", "AVX-512VBMI2", Isa, "AVX-512 byte manipulation 2", "avx512_vbmi2"),
    k("avx512vnni", "AVX-512VNNI", Isa, "AVX-512 neural-network instructions", "avx512_vnni"),
    k("avx512bitalg", "AVX-512BITALG", Isa, "AVX-512 bit algorithms", "avx512_bitalg"),
    k("avx512vpopcntdq", "AVX-512VPOPCNTDQ", Isa, "AVX-512 vector popcount", "avx512_vpopcntdq"),
    n("avx512bf16", "AVX-512BF16", Isa, "AVX-512 bfloat16 operations"),
    n("avx512fp16", "AVX-512FP16", Isa, "AVX-512 IEEE half precision"),
    k("fma", "FMA3", Isa, "Three-operand fused multiply-add", "fma"),
    k("fma4", "FMA4", Isa, "AMD four-operand fused multiply-add", "fma4"),
    k("f16c", "F16C", Isa, "FP16/FP32 conversion", "f16c"),
    k("xop", "XOP", Isa, "AMD extended integer and SIMD operations", "xop"),
    k("tbm", "TBM", Isa, "AMD trailing-bit manipulation", "tbm"),
    k("bmi1", "BMI1", Isa, "Bit extraction and masking", "bmi1"),
    k("bmi2", "BMI2", Isa, "Bit deposit/extract and MULX", "bmi2"),
    k("adx", "ADX", Isa, "Independent carry chains", "adx"),
    k("abm", "ABM / LZCNT", Isa, "Advanced bit manipulation and leading-zero count", "abm"),
    k("popcnt", "POPCNT", Isa, "Population count", "popcnt"),
    k("aes", "AES-NI", Isa, "AES round and key-generation instructions", "aes"),
    k("vaes", "VAES", Isa, "Vector AES", "vaes"),
    k("pclmulqdq", "PCLMULQDQ", Isa, "Carry-less multiplication", "pclmulqdq"),
    k("vpclmulqdq", "VPCLMULQDQ", Isa, "Vector carry-less multiplication", "vpclmulqdq"),
    k("sha", "SHA", Isa, "SHA-1 and SHA-256 acceleration", "sha_ni"),
    k("gfni", "GFNI", Isa, "Galois-field operations", "gfni"),
    k("rdrand", "RDRAND", Isa, "Hardware random values", "rdrand"),
    k("rdseed", "RDSEED", Isa, "Seed-quality entropy", "rdseed"),
    k("clzero", "CLZERO", Isa, "AMD cache-line zeroing", "clzero"),
    k("clflushopt", "CLFLUSHOPT", Isa, "Optimized cache-line flush", "clflushopt"),
    k("clwb", "CLWB", Isa, "Cache-line writeback", "clwb"),
    k("wbnoinvd", "WBNOINVD", Isa, "Write back caches without invalidation", "wbnoinvd"),
    k("movdiri", "MOVDIRI", Isa, "Direct stores to MMIO", "movdiri"),
    k("movdir64b", "MOVDIR64B", Isa, "Direct 64-byte stores", "movdir64b"),
    k("serialize", "SERIALIZE", Isa, "Fully serializing instruction", "serialize"),
    k("rdpid", "RDPID", Isa, "Read a per-CPU identifier", "rdpid"),
    k("rdpru", "RDPRU", Isa, "Read AMD processor register from user mode", "rdpru"),
    k("mwaitx", "MONITORX/MWAITX", Isa, "AMD monitored wait with timeout", "mwaitx"),
    k("cmpxchg16b", "CMPXCHG16B", Isa, "Atomic 128-bit compare-and-exchange", "cx16"),
    k("fsgsbase", "FSGSBASE", Isa, "User-mode FS/GS base access", "fsgsbase"),
    k("xsave", "XSAVE", Isa, "Extended processor-state save/restore", "xsave"),
    k("xsaveopt", "XSAVEOPT", Isa, "Optimized XSAVE", "xsaveopt"),
    k("xsavec", "XSAVEC", Isa, "Compacted XSAVE", "xsavec"),
    k("xsaves", "XSAVES", Isa, "Supervisor-state XSAVE", "xsaves"),

    // Security and memory encryption
    k("nx", "NX", Security, "No-execute page protection", "nx"),
    k("smep", "SMEP", Security, "Supervisor-mode execution prevention", "smep"),
    k("smap", "SMAP", Security, "Supervisor-mode access prevention", "smap"),
    k("umip", "UMIP", Security, "User-mode instruction prevention", "umip"),
    k("pku", "PKU", Security, "User-mode protection keys", "pku"),
    k("ospke", "OSPKE", Security, "OS-enabled protection keys", "ospke"),
    k("sev_snp", "SEV-SNP", Security, "Secure Encrypted Virtualization with integrity protection", "sev_snp"),
    k("sme", "SME", Security, "Secure Memory Encryption", "sme"),
    k("sev", "SEV", Security, "Secure Encrypted Virtualization", "sev"),
    k("sev_es", "SEV-ES", Security, "Encrypted guest register state", "sev_es"),
    n("vmpl", "VMPL", Security, "Virtual-machine privilege levels"),
    n("vte", "SEV-SNP VTE", Security, "Virtual transparent encryption"),
    n("tpm", "TPM", Security, "Trusted Platform Module device"),

    // Kernel vulnerability interface
    v("meltdown", "Meltdown", Vulnerabilities, "Rogue data-cache load"),
    v("spectre_v1", "Spectre v1", Vulnerabilities, "Bounds-check bypass"),
    v("spectre_v2", "Spectre v2", Vulnerabilities, "Branch-target injection"),
    v("spec_store_bypass", "Spectre v4", Vulnerabilities, "Speculative store bypass"),
    v("l1tf", "L1TF", Vulnerabilities, "L1 terminal fault"),
    v("mds", "MDS", Vulnerabilities, "Microarchitectural data sampling"),
    v("tsx_async_abort", "TAA", Vulnerabilities, "TSX asynchronous abort"),
    v("itlb_multihit", "iTLB Multihit", Vulnerabilities, "Instruction-TLB multihit"),
    v("srbds", "SRBDS", Vulnerabilities, "Special-register-buffer sampling"),
    v("mmio_stale_data", "MMIO Stale Data", Vulnerabilities, "Processor MMIO stale data"),
    v("retbleed", "Retbleed", Vulnerabilities, "Return-stack-buffer underflow"),
    v("gather_data_sampling", "GDS", Vulnerabilities, "Gather data sampling"),
    v("reg_file_data_sampling", "RFDS", Vulnerabilities, "Register-file data sampling"),
    v("spec_rstack_overflow", "SRSO", Vulnerabilities, "Speculative return-stack overflow"),
    v("indirect_target_selection", "ITS", Vulnerabilities, "Indirect target selection"),
    v("ghostwrite", "GhostWrite", Vulnerabilities, "Architectural write vulnerability"),
    v("old_microcode", "Old Microcode", Vulnerabilities, "Outdated CPU microcode"),
    v("tsa", "TSA", Vulnerabilities, "Transient scheduler attack"),
    v("vmscape", "VMScape", Vulnerabilities, "Guest-to-host predictor leak"),
    v("vuln_other", "Other (uncatalogued)", Vulnerabilities, "New kernel vulnerability entries"),

    // AMD architectural mitigation capabilities
    k("ibpb", "IBPB", ArchCaps, "Indirect branch prediction barrier", "ibpb"),
    k("ibrs", "IBRS", ArchCaps, "Indirect branch restricted speculation", "ibrs"),
    k("stibp", "STIBP", ArchCaps, "Single-thread indirect branch predictors", "stibp"),
    k("ssbd", "SSBD", ArchCaps, "Speculative store bypass disable", "ssbd"),
    k("virt_ssbd", "Virtual SSBD", ArchCaps, "Guest-visible speculative-store bypass control", "virt_ssbd"),
    k("ssb_no", "SSB_NO", ArchCaps, "Not affected by speculative-store bypass", "ssb_no"),
    k("psfd", "PSFD", ArchCaps, "Predictive store forwarding disable", "psfd"),
    k("btc_no", "BTC_NO", ArchCaps, "Not affected by branch-type confusion", "btc_no"),

    // Virtualization
    k("svm", "AMD-V (SVM)", Virtualization, "Secure Virtual Machine hardware virtualization", "svm"),
    k("hypervisor", "Running under hypervisor", Virtualization, "Guest/VM detection", "hypervisor"),
    n("kvm", "KVM usable", Virtualization, "/dev/kvm present and openable"),
    n("amd_vi", "AMD-Vi / IOMMU", Virtualization, "DMA remapping through ACPI IVRS"),
    k("npt", "Nested Paging", Virtualization, "Second-level guest address translation", "npt"),
    k("lbrv", "LBR Virtualization", Virtualization, "Virtualized last-branch records", "lbrv"),
    k("svm_lock", "SVM Lock", Virtualization, "Firmware lock for SVM enablement", "svm_lock"),
    k("nrip_save", "NRIP Save", Virtualization, "Save next guest RIP on exit", "nrip_save"),
    k("tsc_scale", "TSC Rate MSR", Virtualization, "Guest TSC scaling", "tsc_scale"),
    k("vmcb_clean", "VMCB Clean Bits", Virtualization, "Skip unchanged VMCB state", "vmcb_clean"),
    k("flushbyasid", "Flush by ASID", Virtualization, "Targeted guest-TLB invalidation", "flushbyasid"),
    k("decodeassists", "Decode Assists", Virtualization, "Instruction bytes and operands on VM exit", "decodeassists"),
    k("pausefilter", "Pause Filter", Virtualization, "PAUSE-loop exit filtering", "pausefilter"),
    k("avic", "AVIC", Virtualization, "Advanced virtual interrupt controller", "avic"),
    k("v_vmsave_vmload", "Virtual VMSAVE/VMLOAD", Virtualization, "Accelerated nested virtualization", "v_vmsave_vmload"),
    k("vgif", "Virtual GIF", Virtualization, "Virtual global-interrupt flag", "vgif"),
    v("svm_runtime", "SVM Runtime State", Virtualization, "VM_CR firmware enable and lock state"),

    // Power, topology, performance, QoS
    k("cpb", "Core Performance Boost", Power, "Opportunistic boost clocks", "cpb"),
    k("cppc", "CPPC", Power, "Collaborative processor performance control", "cppc"),
    n("amd_pstate", "amd_pstate driver", Power, "AMD CPPC-backed CPU-frequency driver"),
    n("cpuidle", "CPU idle driver", Power, "Kernel C-state idle driver and states"),
    n("hwmon", "k10temp / AMD hwmon", Power, "CPU temperature and power sensors"),
    n("energy", "AMD energy counters", Power, "AMD powercap or energy-pmu interface"),
    v("pstate_status", "P-state Status", Power, "Current hardware P-state MSR"),
    n("s0ix", "S0ix / s2idle", Power, "Low-power S0 idle"),
    k("x2apic", "x2APIC", Topology, "Extended APIC addressing", "x2apic"),
    k("htt", "Multi-logical package", Topology, "Multiple logical CPUs per package", "ht"),
    n("smt", "SMT", Topology, "Simultaneous multithreading runtime state"),
    k("topoext", "Topology Extensions", Topology, "AMD extended topology leaves", "topoext"),
    k("invariant_tsc", "Invariant TSC", Topology, "Constant-rate timestamp counter", "constant_tsc"),
    k("rdtscp", "RDTSCP", Topology, "Ordered timestamp and processor ID read", "rdtscp"),
    n("hpet", "HPET", Topology, "High-precision event timer"),
    n("numa", "NUMA", Topology, "Non-uniform memory topology"),
    v("memory_channels", "Memory Channels", Topology, "CPU/platform memory-channel capability and observable topology"),
    n("arch_perfmon", "Architectural PMU", Perf, "Architectural performance monitoring"),
    k("ibs", "IBS", Perf, "Instruction-Based Sampling", "ibs"),
    k("perfctr_core", "Core Performance Counters", Perf, "AMD core performance counters", "perfctr_core"),
    k("perfctr_nb", "Northbridge Performance Counters", Perf, "AMD data-fabric counters", "perfctr_nb"),
    k("perfmon_v2", "PerfMon v2", Perf, "AMD extended performance-monitoring interface", "perfmon_v2"),
    n("l3_cat", "L3 Cache Allocation", Rdt, "AMD Platform QoS cache allocation"),
    n("l3_monitoring", "L3 Monitoring", Rdt, "AMD Platform QoS cache monitoring"),
    n("mba", "Memory Bandwidth Allocation", Rdt, "AMD Platform QoS bandwidth control"),
    n("resctrl", "resctrl", Rdt, "Linux resource-control filesystem"),

    // AMD PCI/platform devices
    v("igpu", "Integrated Radeon GPU", Accelerators, "AMD integrated display controller"),
    v("npu", "Ryzen AI NPU", Accelerators, "AMD XDNA neural processor"),
    v("psp", "Platform Security Processor", Accelerators, "AMD PSP / CCP security engine"),
    v("chipset", "AMD Chipset", Platform, "Motherboard chipset identity from DMI and Promontory PCI evidence"),
    v("ethernet", "AMD Ethernet", Platform, "AMD network controller"),
    v("audio", "AMD Audio", Platform, "AMD HD-audio or ACP controller"),
    v("smbus", "AMD SMBus", Platform, "AMD SMBus/I2C controller"),
    v("usb", "AMD USB", Platform, "AMD USB/xHCI controller"),
    v("sata", "AMD SATA", Platform, "AMD SATA/AHCI controller"),
    v("nvme", "AMD NVMe", Platform, "AMD-branded NVMe controller"),
    v("bluetooth", "Bluetooth", Platform, "Bluetooth controller"),
    v("ipmi", "IPMI / BMC", Platform, "Baseboard management controller"),
    n("pmem", "Persistent Memory", Platform, "ACPI NFIT persistent memory"),
    n("cxl", "CXL", Platform, "Compute Express Link"),
    n("hmat", "HMAT / Memory Tiering", Platform, "Heterogeneous memory attributes"),
    v("memory_ecc", "Memory ECC", Platform, "Error-correcting memory"),
    v("memory_dimms", "Installed Memory", Platform, "Populated SMBIOS memory devices"),

    // Firmware
    n("msr", "MSR access", Firmware, "/dev/cpu/*/msr readable"),
    v("hwcr", "AMD HWCR", Firmware, "Hardware Configuration Register value"),
    n("sme_active", "SME Runtime State", Firmware, "Memory-encryption enable state in SYSCFG"),
    n("uefi_boot", "UEFI Boot", Firmware, "Booted through UEFI"),
    n("secure_boot", "Secure Boot", Firmware, "UEFI Secure Boot state"),
    n("setup_mode", "UEFI Setup Mode", Firmware, "Secure Boot key-enrollment mode"),
    n("esrt", "ESRT", Firmware, "UEFI firmware-update resource table"),
    n("wsmt", "WSMT", Firmware, "Windows SMM Security Mitigations Table"),
];

const fn base(
    id: &'static str,
    name: &'static str,
    category: Category,
    description: &'static str,
    flag: Option<&'static str>,
    inline: bool,
) -> FeatureDef {
    FeatureDef {
        id,
        name,
        category,
        description,
        min_privilege: Privilege::User,
        cpuinfo_flag: flag,
        inline_detail: inline,
    }
}
const fn k(
    id: &'static str,
    name: &'static str,
    category: Category,
    description: &'static str,
    flag: &'static str,
) -> FeatureDef {
    base(id, name, category, description, Some(flag), false)
}
const fn n(
    id: &'static str,
    name: &'static str,
    category: Category,
    description: &'static str,
) -> FeatureDef {
    base(id, name, category, description, None, false)
}
const fn v(
    id: &'static str,
    name: &'static str,
    category: Category,
    description: &'static str,
) -> FeatureDef {
    base(id, name, category, description, None, true)
}

pub fn find(id: &str) -> Option<&'static FeatureDef> {
    FEATURES.iter().find(|f| f.id == id)
}
